repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: HEAD
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: checkov
      args: [
        "-d", ".",
      ]
    - id: infracost_breakdown
      args:
        - --args=--path=./env/dev
      verbose: true # Always show costs
    - id: terraform_tflint
      args: [
        "--init",
        "--module",
      ]
    - id: terraform_tfsec
    - id: terraform_validate
